#mysql:
#  server:
#    test1:  #test1数据库的定义，所有参数值都要在前面留一个空格，框架才能识别
#      url: "jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8"
#      username: root
#      password:
#      driverClassName: com.mysql.jdbc.Driver
#      initialSize: 1
#      minIdle: 1
#      maxActive: 50
#    test2: