package test.Dao.Mapper;

import test.Dao.Po.Student;

import java.util.List;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Nov 24 14:23:39 CST 2017
     */
    int insert(Student record);
    void addStudent(Student student);
    Student selectStudentById(String id);
    Student selectStudentByName(String name);
    List<Student> selectAllStudent();
    void updateStudent(Student student);
    void deleteStudentById(String id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Nov 24 14:23:39 CST 2017
     */
    int insertSelective(Student record);
}